openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0
  description: API para gestionar usuarios

servers:
  - url: http://localhost:8080

paths:
  /api/users:
    get:
      summary: Obtiene todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      $ref: './components.yaml#/components/schemas/User'  # Referencia corregida
        '500':
          description: Error interno

  /api/users/{uid}:
    get:
      summary: Obtiene un usuario por ID
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/UserResponse'  # Referencia corregida
        '404':
          description: Usuario no encontrado

    put:
      summary: Actualiza un usuario por ID
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/UpdateUser'  # Referencia corregida
      responses:
        '200':
          description: Usuario actualizado
        '400':
          description: Solicitud inválida
        '404':
          description: Usuario no encontrado

    delete:
      summary: Elimina un usuario por ID
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuario eliminado
        '404':
          description: Usuario no encontrado
